openapi: 3.0.3
info:
  title: Mycelium CDN Registry API
  description: |
    API for the Mycelium CDN Registry service that allows storing and retrieving metadata blobs.
    The service uses Blake3 for content hashing and PostgreSQL for blob storage.
  version: 1.0.0
  contact:
    name: Mycelium CDN Team
servers:
  - url: http://localhost:8080
    description: Local development server
paths:
  /api/v1/metadata/{hash}:
    get:
      summary: Retrieve a metadata blob
      description: |
        Retrieves a metadata blob by its Blake3 hash. The hash must be provided as a 64-character
        hexadecimal string. If the blob is found, its binary content is returned.
      operationId: loadMetadata
      parameters:
        - name: hash
          in: path
          description: 64-character hexadecimal Blake3 hash of the blob
          required: true
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{64}$'
            example: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b'
      responses:
        '200':
          description: Blob content retrieved successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid hash format
        '404':
          description: Blob not found
        '500':
          description: Internal server error
  /api/v1/metadata:
    post:
      summary: Store a metadata blob
      description: |
        Stores a new metadata blob. The blob is hashed using Blake3, and the hash is used as the key
        for future retrieval. The data must be provided as a multipart form with a field named 'data'.
      operationId: saveMetadata
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                data:
                  type: string
                  format: binary
                  description: The binary blob data to store
              required:
                - data
      responses:
        '200':
          description: Blob stored successfully
        '400':
          description: Invalid request format or missing data field
        '500':
          description: Internal server error
components:
  schemas:
    Blob:
      type: object
      description: Represents a stored metadata blob
      properties:
        hash:
          type: string
          format: byte
          description: Blake3 hash of the blob data (32 bytes)
        data:
          type: string
          format: byte
          description: The actual blob data
        size:
          type: integer
          format: int64
          description: Size of the blob data in bytes
        created_at:
          type: string
          format: date-time
          description: Timestamp when the blob was created/uploaded
      required:
        - hash
        - data
        - size
        - created_at
tags:
  - name: Metadata
    description: Operations for storing and retrieving metadata blobs